import {useEffect, useState} from "react"
import supabase from "../utils/supabase"

export default function AnioCarrera({
	carrera,
	slug,
	plan_estudio,
}: {
	carrera: string
	slug: string
	plan_estudio: string | undefined
}) {
	const [anios, setAnios] = useState<string[]>([])

	if (!plan_estudio) return null

	useEffect(() => {
		const fetchAnios = async () => {
			const {data, error} = await supabase
				.from("materias_plan")
				.select("id, plan_id, orientacion_id,materia_id, anio, nro_periodo, nro_optativa, periodo_id")
				.eq("plan_id", plan_estudio)

			if (error || !data) {
				console.error("Error al obtener los anios:", error)
			} else {
				setAnios(data.map((anio) => anio.anio))
			}
		}

		fetchAnios()
	}, [plan_estudio])

	return (
		<section>
			{anios.map((anio) => (
				<h2 key={anio}>{anio}</h2>
			))}
		</section>
	)
}

/* id smallint generated by default as identity not null,
  plan_id bigint not null,
  orientacion_id bigint null,
  materia_id bigint not null,
  anio smallint null,
  nro_periodo smallint null,
  nro_optativa smallint null,
  periodo_id bigint null,
   */
